package hexlet.code;

import java.sql.DriverManager;
import java.sql.SQLException;

public class Application {
    public static void main(String[] args) throws SQLException {
        var connection = DriverManager.getConnection("jdbc:h2:mem:hexlet_test");

        var sql = """
                CREATE TABLE IF NOT EXISTS users (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                username VARCHAR(128) NOT NULL UNIQUE,
                phone VARCHAR(12) NOT NULL UNIQUE
                )
                """;
        var statement = connection.createStatement();
        statement.executeUpdate(sql);
        statement.close();

        var sql2 = """
                INSERT INTO users (username, phone) VALUES
                ('alexey_m', '+79161234567'),
                ('maria.k', '+79261234568'),
                ('dmitry_92', '+79031234569'),
                ('anna_k', '+79051234570'),
                ('ivan_petrov', '+79091234571'),
                ('elena.s', '+79621234572'),
                ('sergey_dev', '+79991234573'),
                ('olga_777', '+79151234574'),
                ('max_power', '+79251234575'),
                ('tatiana_love', '+79011234576'),
                ('andrey_01', '+79021234577'),
                ('natalia_n', '+79041234578'),
                ('pavel_w', '+79061234579'),
                ('irina_star', '+79071234580'),
                ('roman_g', '+79081234581'),
                ('ekaterina_k', '+79101234582'),
                ('artem_pro', '+79111234583'),
                ('svetlana_v', '+79131234584'),
                ('nikolay_88', '+79141234585'),
                ('yulia_yu', '+79171234586'),
                ('vladimir_v', '+79181234587'),
                ('ksenia_k', '+79191234588'),
                ('georgy_g', '+79211234589'),
                ('alina_a', '+79221234590'),
                ('HolyMotherFucker3000', '+79241234591')
                """;
        var statement2 = connection.createStatement();
        statement2.executeUpdate(sql2);
        statement2.close();

        var sql3 = "SELECT * FROM users";
        var statement3 = connection.createStatement();
        var result = statement3.executeQuery(sql3);
        int count = 0;
        while (result.next()) {
            long id = result.getLong("id");
            String username = result.getString("username");
            String phone = result.getString("phone");
            System.out.println("ID: " + id + " Username: " + username + " Phone: " + phone);
            count++;

        }
        System.out.println("Всего записей в БД: " + count);
        statement3.close();
        connection.close();
    }
}
