package hexlet.code;

import java.sql.DriverManager;
import java.sql.SQLException;

public class BasicApplication {
    // Базовый пример Hexlet`a + Самостоятельная работа
    // Нужно указывать базовое исключение,
    // потому что выполнение запросов может привести к исключениям
    public static void main(String[] args) throws SQLException {
        // Создаем соединение с базой в памяти
        // База создается прямо во время выполнения этой строчки
        // mem выбирает базу в памяти, hexlet_test задаёт её имя
        var conn = DriverManager.getConnection("jdbc:h2:mem:hexlet_test");

        var sql =
                "CREATE TABLE users (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                        + " username VARCHAR(255), phone VARCHAR(255))";
        // Чтобы выполнить запрос, создадим объект statement
        var statement = conn.createStatement();
        statement.execute(sql);
        statement.close(); // В конце закрываем

        var sql2 = "INSERT INTO users (username, phone) VALUES ('tommy', '123456789')";
        var statement2 = conn.createStatement();
        statement2.executeUpdate(sql2);
        statement2.close();

        var sql3 = "SELECT * FROM users";
        var statement3 = conn.createStatement();
        // Получаем результат запроса
        var resultSet = statement3.executeQuery(sql3);
        // next() перемещает курсор к следующей строке результата
        while (resultSet.next()) {
            System.out.println(resultSet.getString("username"));
            System.out.println(resultSet.getString("phone"));
        }
        statement3.close();

        var sql4 = """
                INSERT INTO users (username, phone) VALUES
                ('maria', '987654321')
                """;
        var statement4 = conn.createStatement();
        statement4.executeUpdate(sql4);
        statement4.close();

        var sql5 = "SELECT * FROM users ORDER BY id DESC";
        var statement5 = conn.createStatement();
        var result = statement5.executeQuery(sql5);
        while (result.next()) {
            long id =  result.getLong("id");
            String username = result.getString("username");
            String phone = result.getString("phone");
            System.out.println("ID: " + id + ", username: " + username + ", phone: " + phone);
        }
        statement5.close();
        // Закрываем соединение
        conn.close();
    }
}
