package hexlet.code;

import java.sql.DriverManager;
import java.sql.SQLException;

public class DAOExample {
    static void main(String[] args) throws SQLException {
        try (var conn = DriverManager.getConnection("jdbc:h2:mem:dao")) {
            try (var  stmt = conn.createStatement()) {
                stmt.executeUpdate("""
                    CREATE TABLE users (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        username VARCHAR(255),
                        phone VARCHAR(255)
                    )
                    """);
            }

            var dao = new UserDAO(conn);
            var user = new User("Maria", "888888888");
            System.out.println(user.getId()); // Ничего не покажет, т.к. id не установлен.
            dao.save(user);
            System.out.println(user.getId()); // Возможно покажет, но это не точно

            user.setPhone("999999999");
            dao.save(user);

            var saveUser = dao.find(user.getId()).orElseThrow();
            System.out.println(saveUser.getId().equals(user.getId())); // true
            System.out.println(saveUser.getPhone()); // 999999999
            System.out.println(dao.find(99L).isEmpty()); // Не понял

            System.out.println("\n");
            System.out.println(dao.delete(2L));
            System.out.println(dao.delete(1L));
            System.out.println(dao.delete(1L));
            System.out.println(dao.find(1L).isEmpty());
            System.out.println("\n");

            var user2 = new User("John", "888888888");
            var user3 = new User("Jane", "222222222");
            dao.save(user2);
            dao.save(user3);
            System.out.println(user3.getId());
            System.out.println(user2.getId());
            System.out.println(dao.delete(2L));
            System.out.println(dao.find(3L).isEmpty());
        }
    }
}
