package hexlet.code;

import java.sql.DriverManager;
import java.sql.SQLException;

public class StatementApplication {
    // Урок №3 + самостоятельная работа
    static void main(String[] args) throws SQLException {
        try (var connection = DriverManager.getConnection("jdbc:h2:mem:statement_bd")) {
            var sql = """
                    CREATE TABLE users (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    username VARCHAR(128),
                    phone VARCHAR(12))
                    """;
            var sql1 = """
                    INSERT INTO users (username, phone) VALUES (?, ?)
                    """;

            var sql11 = """
                    SELECT * FROM users
                    """;

            var sql2 = """
                    DELETE FROM users
                        WHERE username = ?
                    """;

            try (var statement = connection.createStatement()) {
                statement.execute(sql);
            }

            try (var preparedStatement = connection.prepareStatement(sql1)) {
                preparedStatement.setString(1, "O'Connor");
                preparedStatement.setString(2, "+79319622925");
                preparedStatement.executeUpdate();
                preparedStatement.clearParameters();

                preparedStatement.setString(1, "Tommy");
                preparedStatement.setString(2, "+74233242355");
                preparedStatement.executeUpdate();
                preparedStatement.clearParameters();

                preparedStatement.setString(1, "Maria");
                preparedStatement.setString(2, "+75435346546");
                preparedStatement.executeUpdate();
                preparedStatement.clearParameters();
            }

            try (var statement = connection.createStatement()) {
                var result = statement.executeQuery(sql11);
                System.out.println("База до удаления");
                while (result.next()) {
                    var id = result.getLong("id");
                    var name = result.getString("username");
                    var phone = result.getString("phone");
                    System.out.println("ID: " + id + " username: " + name + " phone: " + phone);
                }
                System.out.println("\n");
            }

            try (var preparedStatement = connection.prepareStatement(sql2)) {
                preparedStatement.setString(1, "O'Connor");
                preparedStatement.executeUpdate();
            }

            try (var statement = connection.createStatement()) {
                var result = statement.executeQuery(sql11);
                System.out.println("База после удаления");
                while (result.next()) {
                    var id = result.getLong("id");
                    var name = result.getString("username");
                    var phone = result.getString("phone");
                    System.out.println("ID: " + id + " username: " + name + " phone: " + phone);
                }
            }
        }
    }
}
