package hexlet.code;

import java.sql.DriverManager;
import java.sql.SQLException;

public class tryWithResourcesApplication {

    public static void main(String[] args) throws SQLException {
        // Урок №2 + самостоятельная работа
        try(var conn = DriverManager.getConnection("jdbc:h2:mem:hexlet_test")) {
            var sql =
                    "CREATE TABLE users (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                            + " username VARCHAR(255), phone VARCHAR(255))";
            try (var statement = conn.createStatement()) {
                statement.execute(sql);
            }

            var sql2 = "INSERT INTO users (username, phone) VALUES ('tommy', '123456789')";
            try (var statement2 = conn.createStatement()) {
                statement2.executeUpdate(sql2);
            }

            var sql3 = "SELECT * FROM users";
            try (var statement3 = conn.createStatement()) {
                var resultSet = statement3.executeQuery(sql3);
                while (resultSet.next()) {
                    System.out.println(resultSet.getString("username"));
                    System.out.println(resultSet.getString("phone"));
                }
            }

            var sql4 = """
                INSERT INTO users (username, phone) VALUES
                ('maria', '987654321')
                """;
            try (var statement4 = conn.createStatement()) {
                statement4.executeUpdate(sql4);
            }

            var sql5 = "SELECT * FROM users ORDER BY id DESC";
            try (var statement5 = conn.createStatement()) {
                var result = statement5.executeQuery(sql5);
                while (result.next()) {
                    long id = result.getLong("id");
                    String username = result.getString("username");
                    String phone = result.getString("phone");
                    System.out.println("ID: " + id + ", username: " + username + ", phone: " + phone);
                }
            }
        }
    }
}
